### ISSUE TITLE
Suggestion! var -> let

### ISSUE THREAD

**Issue by klee214** [egrinberg/Utest#1]
Hello Kate! Do you have any particular reasons for using ```var urlList;```? if not I highly recommend using ```let``` instead of ```var```. As far as I know, '''var''' key is declaring your variable in the very first line globally, which might cause ignoring any block-level variable. If this information is wrong, please let me know! By the way your code is nicer than mine I think lol.

**Comment by katyasichov** [comment]
Fixed
