### ISSUE TITLE
Add/update feature-Lab2

### ISSUE THREAD

**Issue by chawlapalak** [egrinberg/Utest#2]
Hi Ekaterina:

I would like to add this feature to your work for Lab 2:
- In addition to -v  or version, I would also like to add -V also to your code for better user experience.
- add support for timeouts.
- update documentation

Let me know what you think about them, I will make the Pull request for them soon. We can discuss and review it and move ahead with the process.

Regards,
Palak Chawla

**Comment by katyasichov** [comment]
Hi Palak,

Yes sure you can work on these features. Let me know when you create pull request.
