### ISSUE TITLE
Feature: Ignore URL Patterns

### ISSUE THREAD

**Issue by mshinh** [egrinberg/Utest#6]
I would like to work on this feature for lab 4.
-Ignore flag would ignore a list of URL patterns from the original URL list file.
Please let me know if I can proceed. 
Thanks.

**Comment by katyasichov** [comment]
Sure go ahead:)

**Comment by mshinh** [comment]
Hi @egrinberg 

Please check the commit I did to add the ignore url feature to your tool - 8adf38fc0a432a4f216069c32c7fe06a413cc338
Here is forked repo - https://github.com/Shinh18/Utest.git
The brand issue-6 - https://github.com/Shinh18/Utest/tree/issue-6

Let me know if you need any changes. 
Thanks.

**Comment by katyasichov** [comment]
Hey @Shinh18, 
I review your work. Several issues need to be changed:
1. Please update README with new usage 
2. function ignore is not called anywhere so please remove it.
3. A file with anything other than a comment (#) or URL (http://, https://) is invalid.If the file isn't valid, give an appropriate error message and exit.

Please make the changes, let me know when you have done.
I will review it and if everything is covered I will merge.

**Comment by mshinh** [comment]
Hey, I made the required changes. 
Please review.
Thanks

**Comment by katyasichov** [comment]
Merged into lab4 branch. Commit 03eefafb5e13e38e31dcdb08fb627a2abbf46700
